version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      #- npm install
      - pip install pytest

  build:
    commands:
      - echo wepp...
      #- npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo weppp...
      - pytest test_mainfile.py

    #run: |
     #     pytest test_mainfile.py



      
artifacts:
  files:
    - '**/*'
  base-directory: build  # Optional: If your build outputs to a 'build' directory
