version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      #- npm install
      - pip install pytest

  build:
    commands:
      - echo Running tests...
      #- npm test
  post_build:
    commands:
      - echo Build completed on `date`
      - echo weppp...
artifacts:
  files:
    - '**/*'
  base-directory: build  # Optional: If your build outputs to a 'build' directory
